= SeaLion Mission Concept of Operations (ConOps)
:doc-name: mission-conops.adoc
:revnumber: v0.4.0
:toc: left

ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT]
image:https://img.shields.io/badge/Contribute%20on-GitHub-orange[Contribute on GitHub, link=https://github.com/ODU-CGA-CubeSat/mission-conops.git]
image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=https://ODU-CGA-CubeSat.github.io/mission-conops/mission-conops.pdf]
endif::[]

<<<

== Stakeholder Needs
 
The SeaLion Mission Concept of Operations (ConOps) is guided by a series of stakeholder needs, listed below.


=== 1.1: Primary Mission Objective A1
****
The SeaLion mission shall establish UHF communication link with Virginia ground station
**** 




=== 1.2: Primary Mission Objective A2
****
The SeaLion mission shall establish S-Band communication link with MC3 ground station
**** 




=== 1.3: Primary Mission Objective A3
****
The SeaLion mission shall successfully transmit “mission data” defined above to ground stations on the Earth.
**** 




=== 1.4: Primary Mission Objective A4
****
The SeaLion mission shall adhere to CubeSat standards as per CDS Rev. 13
**** 


==== *Reference:*



* https://www.cubesat.org/s/cds_rev13_final2.pdf[CubeSat Design Specification Rev. 13]





=== 2.1: Secondary Mission Objective B1
****
The SeaLion mission shall provide a means to validate an impedance probe in-orbit
**** 




=== 2.2: Secondary Mission Objective B2
****
The SeaLion mission shall provide a means to validate a V-Infrared Sensor (VIR-S) in-orbit
**** 




=== 2.3: Secondary Mission Objective B3
****
The SeaLion mission shall provide a means to validate a deployable composite structure (DeCS) in-orbit
**** 




=== 3.1: Tertiary Mission Objective C1
****
The SeaLion mission shall qualify a newly developed antenna
**** 




=== 3.2: Tertiary Mission Objective C2
****
The SeaLion mission shall qualify a CubeSat bus architecture for very-low Earth orbit (VLEO)
**** 




=== 3.3: Tertiary Mission Objective C3
****
The SeaLion shall verify DeCS in-orbit behavior performance via accelerometer & temperature sensor data
**** 





== User Stories

The SeaLion Mission Concept of Operations (ConOps)'s stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.


=== 1: Ping Satellite

****
As a *Ground Station Operator* I want to *Ping satellite* so that I can *Establish communication link with satellite*.
****

==== Example:

Ping the satellite in order to establish UHF communication link with Virginia ground station


==== *Derived From:*




* xref:{doc-name}#_1_1_primary_mission_objective_a1[Primary Mission Objective A1]






== Data Structures
This section covers each data structure type in the *SeaLion Mission Concept of Operations (ConOps)*.


